@basepath=http://localhost:8080


# @name TEST-GETPOST
GET {{basepath}}/test/test?a=ASD123
Content-Type: application/json
Accept: application/json

{
    "a":1,
    "b":"asd"
}

###
# @name TEST
POST {{basepath}}/test
Content-Type: application/json
Accept: application/json

{
    "a":1,
    "b":"asd"
}

###

# @name STATIC
GET  {{basepath}}/test/a/b/c.html

###

# @name STATIC
GET  {{basepath}}/index.html



###
# @name LOGIN# @name LOGIN
POST {{basepath}}/auth/login

{
    "login":"root",
    "password":"root"
}

###
# @name TEST
POST {{basepath}}/api/authmgr/crud/sec_users
Content-Type: application/json
Accept: application/json
Cookie: SESSIONID=Zm91bmRhdGlvbi5jMWRiZmI0NC05ZTg5LTQyMmMtYWZjOS02ZjE2NmM0OTBjZjAuWEg1WTdWWXNycDhZYU9TVHl5UDBuUT09

{
    "Op":"R"
}


###
# @name NATS-SOME
POST {{basepath}}/some/a/b/c
Content-Type: application/json
Accept: application/json
Cookie: SESSIONID=Zm91bmRhdGlvbi5jMWRiZmI0NC05ZTg5LTQyMmMtYWZjOS02ZjE2NmM0OTBjZjAuWEg1WTdWWXNycDhZYU9TVHl5UDBuUT09

{
  "Op":"R"
}