apiVersion: v1
kind: Pod
metadata:
  name: postgres
  labels:
    role: postgres
spec:
  hostname: postgres
  containers:
    - name: postgres
      image: postgres
      env:
        - name: POSTGRES_PASSWORD
          value: postgres
        - name: PGDATA
          value: /pgdata
      volumeMounts:
        - name: data
          mountPath: /data
      ports:
        - name: postgres
          containerPort: 5432
          hostPort: 5432
          protocol: TCP
  volumes:
  - name: data
    persistentVolumeClaim:
      claimName: postgres-pvc