apiVersion: v1
kind: Pod
metadata:
  name: gw
  labels:
    role: gw
spec:
  hostname: gw
  containers:
    - name: gw
      image:  digitalcircle/foundation-gw:latest
      ports:
        - name: gw
          containerPort: 8080
          hostPort: 8080
          protocol: TCP