apiVersion: v1
kind: Pod
metadata:
  name: nats
  labels:
    role: nats
spec:
  containers:
    - name: nats
      image: digitalcircle/foundation-nats-server
      ports:
        - name: nats
          containerPort: 4222
          hostPort: 4222
          protocol: TCP
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgres-pvc
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: local-path
  resources:
    requests:
      storage: 5Gi
---
apiVersion: v1
kind: Pod
metadata:
  name: postgres
  labels:
    role: postgres
spec:
  containers:
    - name: postgres
      image: postgres
      env:
        - name: POSTGRES_PASSWORD
          value: postgres
        - name: PGDATA
          value: /pgdata
      volumeMounts:
        - name: data
          mountPath: /data
      ports:
        - name: postgres
          containerPort: 5432
          hostPort: 5432
          protocol: TCP
  volumes:
  - name: data
    persistentVolumeClaim:
      claimName: postgres-pvc